/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "byzantine.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };
int N=2; //i will wait for answers from 2 peers
int resultReceived = 0;
static ORDER_MESSAGE dataFromPeers[2];
/*
 void eachresult(char *out, struct sockaddr_in *addr)
{
	fprintf(stderr,"%s ","the call back of broadcast function called\n");
	
}
*/
void *
receiveorder_1(ORDER_MESSAGE *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
/*
	enum clnt_stat retval = clnt_broadcast(BYZANTINE,
                     BYZANTINEVERS, receiveOrder,
                     (xdrproc_t) xdr_ORDER_MESSAGE,  (caddr_t) argp,
                     (xdrproc_t) xdr_void, (caddr_t) &clnt_res,
                     eachresult);
	fprintf(stderr,"ret value of broadcast is %d\n",retval);

*/	

	if (clnt_call (clnt, receiveOrder,
		(xdrproc_t) xdr_ORDER_MESSAGE, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		
		return (NULL);
	}

	return ((void *)&clnt_res);
}



ORDER_MESSAGE *
sendmeorderyougot_1(void *argp, CLIENT *clnt)
{
	 ORDER_MESSAGE clnt_res;
	
	fprintf(stderr,"sending sendmeorderyougot message\n");
	
	memset((char *)&clnt_res, '0', sizeof(clnt_res));

		
	if (clnt_call (clnt, SendMeOrderYouGot,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_ORDER_MESSAGE, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
