/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BYZANTINE_H_RPCGEN
#define _BYZANTINE_H_RPCGEN

#include <rpc/rpc.h>
#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct ORDER_MESSAGE {
	int orderValue;
	int srcID;
	char *sourceIP;
};
typedef struct ORDER_MESSAGE ORDER_MESSAGE;

#define BYZANTINE 0x44553344
#define BYZANTINEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define receiveOrder 1
extern int HOSTID;
extern int ISBYZANTINE;
extern int orderFromInitiator;
extern int isOrderReceived;
extern int initiator;
extern  void * receiveorder_1(ORDER_MESSAGE *, CLIENT *);
extern  void * receiveorder_1_svc(ORDER_MESSAGE *, struct svc_req *);
#define SendMeOrderYouGot 2
extern  ORDER_MESSAGE * sendmeorderyougot_1(void *, CLIENT *);
extern  ORDER_MESSAGE * sendmeorderyougot_1_svc(void *, struct svc_req *);
extern int byzantine_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);
extern void* clientFunc();
extern int serverFunc ();
#else /* K&R C */
#define receiveOrder 1
extern int HOSTID;
extern int ISBYZANTINE;
extern int orderFromInitiator;
extern int isOrderReceived;
extern int initiator;
extern  void * receiveorder_1();
extern  void * receiveorder_1_svc();
#define SendMeOrderYouGot 2
extern  ORDER_MESSAGE * sendmeorderyougot_1();
extern  ORDER_MESSAGE * sendmeorderyougot_1_svc();
extern int byzantine_1_freeresult ();
extern void* clientFunc();
extern int serverFunc ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ORDER_MESSAGE (XDR *, ORDER_MESSAGE*);

#else /* K&R C */
extern bool_t xdr_ORDER_MESSAGE ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BYZANTINE_H_RPCGEN */
