
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = byzantine_client
SERVER = byzantine_server

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = byzantine.x

TARGETS_SVC.c = byzantine_svc.c byzantine_server.c byzantine_xdr.c 
TARGETS_CLNT.c = byzantine_clnt.c byzantine_client.c byzantine_xdr.c byzantine_svc.c byzantine_server.c 
TARGETS = byzantine.h byzantine_xdr.c byzantine_clnt.c byzantine_svc.c byzantine_client.c byzantine_server.c

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)
# Compiler flags 

CFLAGS += -g -DRPC_SVC_FG

LDLIBS += -lnsl -pthread
RPCGENFLAGS = 

# Targets 

all : $(CLIENT)

$(TARGETS) : $(SOURCES.x) 
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c) 

$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(TARGETS_SVC.c) 

$(CLIENT) : $(OBJECTS_CLNT) 
	$(LINK.c) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(LINK.c) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

 clean:
	 $(RM) core $(TARGETS) $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER)

